"""Compatibility re-exports for Telegram conversation handlers."""

from telegram_bot.conversation_common import (
    _parse_duration_minutes,
    _parse_time_text,
    _validate_duration_minutes,
    cancel_conversation,
)
from telegram_bot.conversation_create_meeting import (
    CreateMeetingStates,
    confirm_meeting_callback,
    create_meeting_start,
    get_create_meeting_conversation,
    input_meeting_name_handler,
    input_meeting_url_handler,
    select_provider_callback,
)
from telegram_bot.conversation_create_schedule import (
    CreateScheduleStates,
    confirm_schedule_callback,
    create_schedule_start,
    get_create_schedule_conversation,
    input_custom_duration_handler,
    input_custom_time_handler,
    select_duration_callback,
    select_meeting_callback,
    select_time_callback,
    select_youtube_callback,
)
from telegram_bot.conversation_edit_schedule import (
    EditScheduleStates,
    edit_confirm_callback,
    edit_delete_confirm_callback,
    edit_input_custom_time_handler,
    edit_schedule_start,
    edit_select_schedule_callback,
    edit_select_time_callback,
    get_edit_schedule_conversation,
)

__all__ = [
    "CreateMeetingStates",
    "CreateScheduleStates",
    "EditScheduleStates",
    "_parse_duration_minutes",
    "_parse_time_text",
    "_validate_duration_minutes",
    "cancel_conversation",
    "confirm_meeting_callback",
    "confirm_schedule_callback",
    "create_meeting_start",
    "create_schedule_start",
    "edit_confirm_callback",
    "edit_delete_confirm_callback",
    "edit_input_custom_time_handler",
    "edit_schedule_start",
    "edit_select_schedule_callback",
    "edit_select_time_callback",
    "get_create_meeting_conversation",
    "get_create_schedule_conversation",
    "get_edit_schedule_conversation",
    "input_custom_duration_handler",
    "input_custom_time_handler",
    "input_meeting_name_handler",
    "input_meeting_url_handler",
    "select_duration_callback",
    "select_meeting_callback",
    "select_provider_callback",
    "select_time_callback",
    "select_youtube_callback",
]
